database:
  connection:
    host: "mongo"
    port: 27017
    username: "admin"  # Leave empty if no authentication is required
    password: "password"  # Leave empty if no authentication is required
  settings:
    name: "digital_twin_db"  # Your database name
    auth_source: "admin"